//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pwa.FrameWork.Dao.EF.Smart1662
{
    using System;
    using System.Collections.Generic;
    
    public partial class CIS_TB_MS_AMPHUR
    {
        public string CODE { get; set; }
        public string NAME { get; set; }
        public string PROVINCE_CODE { get; set; }
        public string ACTIVE { get; set; }
        public Nullable<int> ORG_OWNER_ID { get; set; }
        public Nullable<int> ORG_USER_ID { get; set; }
        public Nullable<int> UPDATE_BY { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
    }
}
