//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pwa.FrameWork.Dao.EF.Smart1662
{
    using System;
    using System.Collections.Generic;
    
    public partial class CIS_TB_LT_USETYPE
    {
        public int ID { get; set; }
        public string USETYPE { get; set; }
        public string USENAME { get; set; }
        public int CUSTGROUP_ID { get; set; }
        public string GOVFLAG { get; set; }
        public int CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public Nullable<int> UPDATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE { get; set; }
        public string IS_DELETED { get; set; }
        public int ORG_OWNER_ID { get; set; }
        public int ORG_USER_ID { get; set; }
        public Nullable<int> CALCULATE_GROUP { get; set; }
        public Nullable<int> BULKSALES_TYPE_ID { get; set; }
        public string DTSFLAG { get; set; }
        public string INSFLAG { get; set; }
        public Nullable<int> N_ID { get; set; }
        public string N_USETYPE { get; set; }
        public string N_USENAME { get; set; }
        public Nullable<int> N_CUSTGROUP_ID { get; set; }
        public string MIN_USE { get; set; }
        public string USE_VAT { get; set; }
        public string GROUP_PROMO { get; set; }
    }
}
