//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pwa.FrameWork.Dao.EF.Smart1662
{
    using System;
    using System.Collections.Generic;
    
    public partial class CISAmphure
    {
        public string AmphureId { get; set; }
        public string AmphureName { get; set; }
        public string ProvinceId { get; set; }
        public string ACTIVE { get; set; }
        public Nullable<double> ORG_OWNER_ID { get; set; }
        public Nullable<double> ORG_USER_ID { get; set; }
        public string UPDATE_BY { get; set; }
        public string UPDATE_DATE { get; set; }
    }
}
