//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pwa.FrameWork.Dao.EF.Smart1662
{
    using System;
    using System.Collections.Generic;
    
    public partial class PwaInformer
    {
        public int InformerID { get; set; }
        public int PwaIncidentID { get; set; }
        public string CustomerID { get; set; }
        public string CustCode { get; set; }
        public string Title { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MeterNo { get; set; }
        public string Telephone { get; set; }
        public string InformChannelID { get; set; }
        public string InformReference { get; set; }
        public string ProvinceID { get; set; }
        public string DistrictID { get; set; }
        public string SubDistrictID { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string Email { get; set; }
        public string FaceBook { get; set; }
        public string ICustomerType { get; set; }
        public string Address_no { get; set; }
        public string Village_no { get; set; }
        public string Village { get; set; }
        public string Building { get; set; }
        public string Floor { get; set; }
        public string Soi { get; set; }
        public string Road { get; set; }
    }
}
