//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pwa.FrameWork.Dao.EF.Smart1662
{
    using System;
    using System.Collections.Generic;
    
    public partial class PwaIncident
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PwaIncident()
        {
            this.PwaIncidentSmsTrack = new HashSet<PwaIncidentSmsTrack>();
        }
    
        public int PwaIncidentID { get; set; }
        public string PwaIncidentNo { get; set; }
        public string PwaIncidentTypeID { get; set; }
        public string PwaIncidentGroupID { get; set; }
        public string CaseTitle { get; set; }
        public string CaseTitleDetail { get; set; }
        public string CaseDetail { get; set; }
        public string ResolvedDetail { get; set; }
        public bool Sla { get; set; }
        public string SlaDetail { get; set; }
        public System.DateTime ReceivedCaseDate { get; set; }
        public Nullable<System.DateTime> CompletedCaseDate { get; set; }
        public string CaseLatitude { get; set; }
        public string CaseLongtitude { get; set; }
        public string PwsIncidentAddress { get; set; }
        public int ProcessStage { get; set; }
        public int CustomerProcessStage { get; set; }
        public string PwaParentIncidentID { get; set; }
        public int Status { get; set; }
        public string PwaInformReceiver { get; set; }
        public Nullable<System.DateTime> PwaInformDate { get; set; }
        public string BracnchNo { get; set; }
        public string Recorder { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
        public string ImageFilePath { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedBA { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public string UpdatedBA { get; set; }
        public string RandomNo { get; set; }
        public string Reason { get; set; }
        public string SysOwnerCode { get; set; }
        public Nullable<System.DateTime> StartSLADate { get; set; }
        public Nullable<System.DateTime> EndSLADate { get; set; }
        public string InformLatitude { get; set; }
        public string InformLongtitude { get; set; }
        public string CommentID { get; set; }
        public Nullable<bool> SlaStatus { get; set; }
        public Nullable<int> MinuteWorking { get; set; }
        public Nullable<int> OverSlaId { get; set; }
        public string OverSlaOther { get; set; }
        public string AddressNo { get; set; }
        public string VillageNo { get; set; }
        public string VillageBuilding { get; set; }
        public string Soi { get; set; }
        public string Road { get; set; }
        public string SubDistrictID { get; set; }
        public string DistrictID { get; set; }
        public string ProvinceID { get; set; }
        public string NearLocate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PwaIncidentSmsTrack> PwaIncidentSmsTrack { get; set; }
    }
}
