//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pwa.FrameWork.Dao.EF.Smart1662
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysStatus
    {
        public int status_id { get; set; }
        public string status_name_th { get; set; }
        public string status_name_en { get; set; }
        public string desc { get; set; }
        public Nullable<int> dept_id { get; set; }
        public string public_status { get; set; }
    }
}
