//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Pwa.Web.ReportFiles.DataSources {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("GUI_015")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class GUI_015 : global::System.Data.DataSet {
        
        private GUI_015DataTable tableGUI_015;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        public GUI_015() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        protected GUI_015(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["GUI_015"] != null)) {
                    base.Tables.Add(new GUI_015DataTable(ds.Tables["GUI_015"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public GUI_015DataTable _GUI_015 {
            get {
                return this.tableGUI_015;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        public override global::System.Data.DataSet Clone() {
            GUI_015 cln = ((GUI_015)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["GUI_015"] != null)) {
                    base.Tables.Add(new GUI_015DataTable(ds.Tables["GUI_015"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        internal void InitVars(bool initTable) {
            this.tableGUI_015 = ((GUI_015DataTable)(base.Tables["GUI_015"]));
            if ((initTable == true)) {
                if ((this.tableGUI_015 != null)) {
                    this.tableGUI_015.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        private void InitClass() {
            this.DataSetName = "GUI_015";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/GUI_015.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableGUI_015 = new GUI_015DataTable();
            base.Tables.Add(this.tableGUI_015);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        private bool ShouldSerialize_GUI_015() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            GUI_015 ds = new GUI_015();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        public delegate void GUI_015RowChangeEventHandler(object sender, GUI_015RowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class GUI_015DataTable : global::System.Data.TypedTableBase<GUI_015Row> {
            
            private global::System.Data.DataColumn columnROW_NO;
            
            private global::System.Data.DataColumn columnBRANCH;
            
            private global::System.Data.DataColumn columnAMOUNT;
            
            private global::System.Data.DataColumn columnCAT01_AMOUNT;
            
            private global::System.Data.DataColumn columnCAT01_NOT_OVERDUE;
            
            private global::System.Data.DataColumn columnCAT01_OVERDUE;
            
            private global::System.Data.DataColumn columnCAT02_AMOUNT;
            
            private global::System.Data.DataColumn columnCAT02_NOT_OVERDUE;
            
            private global::System.Data.DataColumn columnCAT02_OVERDUE;
            
            private global::System.Data.DataColumn columnCAT03_AMOUNT;
            
            private global::System.Data.DataColumn columnCAT03_NOT_OVERDUE;
            
            private global::System.Data.DataColumn columnCAT03_OVERDUE;
            
            private global::System.Data.DataColumn columnCAT04_AMOUNT;
            
            private global::System.Data.DataColumn columnCAT04_NOT_OVERDUE;
            
            private global::System.Data.DataColumn columnCAT04_OVERDUE;
            
            private global::System.Data.DataColumn columnCAT05_AMOUNT;
            
            private global::System.Data.DataColumn columnCAT05_NOT_OVERDUE;
            
            private global::System.Data.DataColumn columnCAT05_OVERDUE;
            
            private global::System.Data.DataColumn columnPOINT;
            
            private global::System.Data.DataColumn columnAMOUNT_TOTAL;
            
            private global::System.Data.DataColumn columnAMOUNT_TOTAL_NOT_OVERDUE;
            
            private global::System.Data.DataColumn columnSLA50PERCEN;
            
            private global::System.Data.DataColumn columnPOINT_OF_INTENSIVE;
            
            private global::System.Data.DataColumn columnTOTAL_AMOUNT;
            
            private global::System.Data.DataColumn columnCAT06_AMOUNT;
            
            private global::System.Data.DataColumn columnCAT06_NOT_OVERDUE;
            
            private global::System.Data.DataColumn columnCAT06_OVERDUE;
            
            private global::System.Data.DataColumn columnCAL30PERCEN;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public GUI_015DataTable() {
                this.TableName = "GUI_015";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            internal GUI_015DataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected GUI_015DataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn ROW_NOColumn {
                get {
                    return this.columnROW_NO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn BRANCHColumn {
                get {
                    return this.columnBRANCH;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn AMOUNTColumn {
                get {
                    return this.columnAMOUNT;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn CAT01_AMOUNTColumn {
                get {
                    return this.columnCAT01_AMOUNT;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn CAT01_NOT_OVERDUEColumn {
                get {
                    return this.columnCAT01_NOT_OVERDUE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn CAT01_OVERDUEColumn {
                get {
                    return this.columnCAT01_OVERDUE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn CAT02_AMOUNTColumn {
                get {
                    return this.columnCAT02_AMOUNT;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn CAT02_NOT_OVERDUEColumn {
                get {
                    return this.columnCAT02_NOT_OVERDUE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn CAT02_OVERDUEColumn {
                get {
                    return this.columnCAT02_OVERDUE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn CAT03_AMOUNTColumn {
                get {
                    return this.columnCAT03_AMOUNT;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn CAT03_NOT_OVERDUEColumn {
                get {
                    return this.columnCAT03_NOT_OVERDUE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn CAT03_OVERDUEColumn {
                get {
                    return this.columnCAT03_OVERDUE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn CAT04_AMOUNTColumn {
                get {
                    return this.columnCAT04_AMOUNT;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn CAT04_NOT_OVERDUEColumn {
                get {
                    return this.columnCAT04_NOT_OVERDUE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn CAT04_OVERDUEColumn {
                get {
                    return this.columnCAT04_OVERDUE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn CAT05_AMOUNTColumn {
                get {
                    return this.columnCAT05_AMOUNT;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn CAT05_NOT_OVERDUEColumn {
                get {
                    return this.columnCAT05_NOT_OVERDUE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn CAT05_OVERDUEColumn {
                get {
                    return this.columnCAT05_OVERDUE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn POINTColumn {
                get {
                    return this.columnPOINT;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn AMOUNT_TOTALColumn {
                get {
                    return this.columnAMOUNT_TOTAL;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn AMOUNT_TOTAL_NOT_OVERDUEColumn {
                get {
                    return this.columnAMOUNT_TOTAL_NOT_OVERDUE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn SLA50PERCENColumn {
                get {
                    return this.columnSLA50PERCEN;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn POINT_OF_INTENSIVEColumn {
                get {
                    return this.columnPOINT_OF_INTENSIVE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn TOTAL_AMOUNTColumn {
                get {
                    return this.columnTOTAL_AMOUNT;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn CAT06_AMOUNTColumn {
                get {
                    return this.columnCAT06_AMOUNT;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn CAT06_NOT_OVERDUEColumn {
                get {
                    return this.columnCAT06_NOT_OVERDUE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn CAT06_OVERDUEColumn {
                get {
                    return this.columnCAT06_OVERDUE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn CAL30PERCENColumn {
                get {
                    return this.columnCAL30PERCEN;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public GUI_015Row this[int index] {
                get {
                    return ((GUI_015Row)(this.Rows[index]));
                }
            }
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public event GUI_015RowChangeEventHandler GUI_015RowChanging;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public event GUI_015RowChangeEventHandler GUI_015RowChanged;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public event GUI_015RowChangeEventHandler GUI_015RowDeleting;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public event GUI_015RowChangeEventHandler GUI_015RowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void AddGUI_015Row(GUI_015Row row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public GUI_015Row AddGUI_015Row(
                        string ROW_NO, 
                        string BRANCH, 
                        string AMOUNT, 
                        string CAT01_AMOUNT, 
                        string CAT01_NOT_OVERDUE, 
                        string CAT01_OVERDUE, 
                        string CAT02_AMOUNT, 
                        string CAT02_NOT_OVERDUE, 
                        string CAT02_OVERDUE, 
                        string CAT03_AMOUNT, 
                        string CAT03_NOT_OVERDUE, 
                        string CAT03_OVERDUE, 
                        string CAT04_AMOUNT, 
                        string CAT04_NOT_OVERDUE, 
                        string CAT04_OVERDUE, 
                        string CAT05_AMOUNT, 
                        string CAT05_NOT_OVERDUE, 
                        string CAT05_OVERDUE, 
                        string POINT, 
                        string AMOUNT_TOTAL, 
                        string AMOUNT_TOTAL_NOT_OVERDUE, 
                        string SLA50PERCEN, 
                        string POINT_OF_INTENSIVE, 
                        string TOTAL_AMOUNT, 
                        string CAT06_AMOUNT, 
                        string CAT06_NOT_OVERDUE, 
                        string CAT06_OVERDUE, 
                        string CAL30PERCEN) {
                GUI_015Row rowGUI_015Row = ((GUI_015Row)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        ROW_NO,
                        BRANCH,
                        AMOUNT,
                        CAT01_AMOUNT,
                        CAT01_NOT_OVERDUE,
                        CAT01_OVERDUE,
                        CAT02_AMOUNT,
                        CAT02_NOT_OVERDUE,
                        CAT02_OVERDUE,
                        CAT03_AMOUNT,
                        CAT03_NOT_OVERDUE,
                        CAT03_OVERDUE,
                        CAT04_AMOUNT,
                        CAT04_NOT_OVERDUE,
                        CAT04_OVERDUE,
                        CAT05_AMOUNT,
                        CAT05_NOT_OVERDUE,
                        CAT05_OVERDUE,
                        POINT,
                        AMOUNT_TOTAL,
                        AMOUNT_TOTAL_NOT_OVERDUE,
                        SLA50PERCEN,
                        POINT_OF_INTENSIVE,
                        TOTAL_AMOUNT,
                        CAT06_AMOUNT,
                        CAT06_NOT_OVERDUE,
                        CAT06_OVERDUE,
                        CAL30PERCEN};
                rowGUI_015Row.ItemArray = columnValuesArray;
                this.Rows.Add(rowGUI_015Row);
                return rowGUI_015Row;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public override global::System.Data.DataTable Clone() {
                GUI_015DataTable cln = ((GUI_015DataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected override global::System.Data.DataTable CreateInstance() {
                return new GUI_015DataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            internal void InitVars() {
                this.columnROW_NO = base.Columns["ROW_NO"];
                this.columnBRANCH = base.Columns["BRANCH"];
                this.columnAMOUNT = base.Columns["AMOUNT"];
                this.columnCAT01_AMOUNT = base.Columns["CAT01_AMOUNT"];
                this.columnCAT01_NOT_OVERDUE = base.Columns["CAT01_NOT_OVERDUE"];
                this.columnCAT01_OVERDUE = base.Columns["CAT01_OVERDUE"];
                this.columnCAT02_AMOUNT = base.Columns["CAT02_AMOUNT"];
                this.columnCAT02_NOT_OVERDUE = base.Columns["CAT02_NOT_OVERDUE"];
                this.columnCAT02_OVERDUE = base.Columns["CAT02_OVERDUE"];
                this.columnCAT03_AMOUNT = base.Columns["CAT03_AMOUNT"];
                this.columnCAT03_NOT_OVERDUE = base.Columns["CAT03_NOT_OVERDUE"];
                this.columnCAT03_OVERDUE = base.Columns["CAT03_OVERDUE"];
                this.columnCAT04_AMOUNT = base.Columns["CAT04_AMOUNT"];
                this.columnCAT04_NOT_OVERDUE = base.Columns["CAT04_NOT_OVERDUE"];
                this.columnCAT04_OVERDUE = base.Columns["CAT04_OVERDUE"];
                this.columnCAT05_AMOUNT = base.Columns["CAT05_AMOUNT"];
                this.columnCAT05_NOT_OVERDUE = base.Columns["CAT05_NOT_OVERDUE"];
                this.columnCAT05_OVERDUE = base.Columns["CAT05_OVERDUE"];
                this.columnPOINT = base.Columns["POINT"];
                this.columnAMOUNT_TOTAL = base.Columns["AMOUNT_TOTAL"];
                this.columnAMOUNT_TOTAL_NOT_OVERDUE = base.Columns["AMOUNT_TOTAL_NOT_OVERDUE"];
                this.columnSLA50PERCEN = base.Columns["SLA50PERCEN"];
                this.columnPOINT_OF_INTENSIVE = base.Columns["POINT_OF_INTENSIVE"];
                this.columnTOTAL_AMOUNT = base.Columns["TOTAL_AMOUNT"];
                this.columnCAT06_AMOUNT = base.Columns["CAT06_AMOUNT"];
                this.columnCAT06_NOT_OVERDUE = base.Columns["CAT06_NOT_OVERDUE"];
                this.columnCAT06_OVERDUE = base.Columns["CAT06_OVERDUE"];
                this.columnCAL30PERCEN = base.Columns["CAL30PERCEN"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            private void InitClass() {
                this.columnROW_NO = new global::System.Data.DataColumn("ROW_NO", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnROW_NO);
                this.columnBRANCH = new global::System.Data.DataColumn("BRANCH", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnBRANCH);
                this.columnAMOUNT = new global::System.Data.DataColumn("AMOUNT", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnAMOUNT);
                this.columnCAT01_AMOUNT = new global::System.Data.DataColumn("CAT01_AMOUNT", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCAT01_AMOUNT);
                this.columnCAT01_NOT_OVERDUE = new global::System.Data.DataColumn("CAT01_NOT_OVERDUE", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCAT01_NOT_OVERDUE);
                this.columnCAT01_OVERDUE = new global::System.Data.DataColumn("CAT01_OVERDUE", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCAT01_OVERDUE);
                this.columnCAT02_AMOUNT = new global::System.Data.DataColumn("CAT02_AMOUNT", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCAT02_AMOUNT);
                this.columnCAT02_NOT_OVERDUE = new global::System.Data.DataColumn("CAT02_NOT_OVERDUE", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCAT02_NOT_OVERDUE);
                this.columnCAT02_OVERDUE = new global::System.Data.DataColumn("CAT02_OVERDUE", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCAT02_OVERDUE);
                this.columnCAT03_AMOUNT = new global::System.Data.DataColumn("CAT03_AMOUNT", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCAT03_AMOUNT);
                this.columnCAT03_NOT_OVERDUE = new global::System.Data.DataColumn("CAT03_NOT_OVERDUE", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCAT03_NOT_OVERDUE);
                this.columnCAT03_OVERDUE = new global::System.Data.DataColumn("CAT03_OVERDUE", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCAT03_OVERDUE);
                this.columnCAT04_AMOUNT = new global::System.Data.DataColumn("CAT04_AMOUNT", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCAT04_AMOUNT);
                this.columnCAT04_NOT_OVERDUE = new global::System.Data.DataColumn("CAT04_NOT_OVERDUE", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCAT04_NOT_OVERDUE);
                this.columnCAT04_OVERDUE = new global::System.Data.DataColumn("CAT04_OVERDUE", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCAT04_OVERDUE);
                this.columnCAT05_AMOUNT = new global::System.Data.DataColumn("CAT05_AMOUNT", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCAT05_AMOUNT);
                this.columnCAT05_NOT_OVERDUE = new global::System.Data.DataColumn("CAT05_NOT_OVERDUE", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCAT05_NOT_OVERDUE);
                this.columnCAT05_OVERDUE = new global::System.Data.DataColumn("CAT05_OVERDUE", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCAT05_OVERDUE);
                this.columnPOINT = new global::System.Data.DataColumn("POINT", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPOINT);
                this.columnAMOUNT_TOTAL = new global::System.Data.DataColumn("AMOUNT_TOTAL", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnAMOUNT_TOTAL);
                this.columnAMOUNT_TOTAL_NOT_OVERDUE = new global::System.Data.DataColumn("AMOUNT_TOTAL_NOT_OVERDUE", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnAMOUNT_TOTAL_NOT_OVERDUE);
                this.columnSLA50PERCEN = new global::System.Data.DataColumn("SLA50PERCEN", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSLA50PERCEN);
                this.columnPOINT_OF_INTENSIVE = new global::System.Data.DataColumn("POINT_OF_INTENSIVE", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPOINT_OF_INTENSIVE);
                this.columnTOTAL_AMOUNT = new global::System.Data.DataColumn("TOTAL_AMOUNT", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTOTAL_AMOUNT);
                this.columnCAT06_AMOUNT = new global::System.Data.DataColumn("CAT06_AMOUNT", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCAT06_AMOUNT);
                this.columnCAT06_NOT_OVERDUE = new global::System.Data.DataColumn("CAT06_NOT_OVERDUE", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCAT06_NOT_OVERDUE);
                this.columnCAT06_OVERDUE = new global::System.Data.DataColumn("CAT06_OVERDUE", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCAT06_OVERDUE);
                this.columnCAL30PERCEN = new global::System.Data.DataColumn("CAL30PERCEN", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCAL30PERCEN);
                this.ExtendedProperties.Add("Generator_TablePropName", "_GUI_015");
                this.ExtendedProperties.Add("Generator_UserTableName", "GUI_015");
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public GUI_015Row NewGUI_015Row() {
                return ((GUI_015Row)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new GUI_015Row(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected override global::System.Type GetRowType() {
                return typeof(GUI_015Row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.GUI_015RowChanged != null)) {
                    this.GUI_015RowChanged(this, new GUI_015RowChangeEvent(((GUI_015Row)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.GUI_015RowChanging != null)) {
                    this.GUI_015RowChanging(this, new GUI_015RowChangeEvent(((GUI_015Row)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.GUI_015RowDeleted != null)) {
                    this.GUI_015RowDeleted(this, new GUI_015RowChangeEvent(((GUI_015Row)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.GUI_015RowDeleting != null)) {
                    this.GUI_015RowDeleting(this, new GUI_015RowChangeEvent(((GUI_015Row)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void RemoveGUI_015Row(GUI_015Row row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                GUI_015 ds = new GUI_015();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "GUI_015DataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        public partial class GUI_015Row : global::System.Data.DataRow {
            
            private GUI_015DataTable tableGUI_015;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            internal GUI_015Row(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableGUI_015 = ((GUI_015DataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string ROW_NO {
                get {
                    try {
                        return ((string)(this[this.tableGUI_015.ROW_NOColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ROW_NO\' in table \'GUI_015\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableGUI_015.ROW_NOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string BRANCH {
                get {
                    try {
                        return ((string)(this[this.tableGUI_015.BRANCHColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'BRANCH\' in table \'GUI_015\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableGUI_015.BRANCHColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string AMOUNT {
                get {
                    try {
                        return ((string)(this[this.tableGUI_015.AMOUNTColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'AMOUNT\' in table \'GUI_015\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableGUI_015.AMOUNTColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string CAT01_AMOUNT {
                get {
                    try {
                        return ((string)(this[this.tableGUI_015.CAT01_AMOUNTColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'CAT01_AMOUNT\' in table \'GUI_015\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableGUI_015.CAT01_AMOUNTColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string CAT01_NOT_OVERDUE {
                get {
                    try {
                        return ((string)(this[this.tableGUI_015.CAT01_NOT_OVERDUEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'CAT01_NOT_OVERDUE\' in table \'GUI_015\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableGUI_015.CAT01_NOT_OVERDUEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string CAT01_OVERDUE {
                get {
                    try {
                        return ((string)(this[this.tableGUI_015.CAT01_OVERDUEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'CAT01_OVERDUE\' in table \'GUI_015\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableGUI_015.CAT01_OVERDUEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string CAT02_AMOUNT {
                get {
                    try {
                        return ((string)(this[this.tableGUI_015.CAT02_AMOUNTColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'CAT02_AMOUNT\' in table \'GUI_015\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableGUI_015.CAT02_AMOUNTColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string CAT02_NOT_OVERDUE {
                get {
                    try {
                        return ((string)(this[this.tableGUI_015.CAT02_NOT_OVERDUEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'CAT02_NOT_OVERDUE\' in table \'GUI_015\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableGUI_015.CAT02_NOT_OVERDUEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string CAT02_OVERDUE {
                get {
                    try {
                        return ((string)(this[this.tableGUI_015.CAT02_OVERDUEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'CAT02_OVERDUE\' in table \'GUI_015\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableGUI_015.CAT02_OVERDUEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string CAT03_AMOUNT {
                get {
                    try {
                        return ((string)(this[this.tableGUI_015.CAT03_AMOUNTColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'CAT03_AMOUNT\' in table \'GUI_015\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableGUI_015.CAT03_AMOUNTColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string CAT03_NOT_OVERDUE {
                get {
                    try {
                        return ((string)(this[this.tableGUI_015.CAT03_NOT_OVERDUEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'CAT03_NOT_OVERDUE\' in table \'GUI_015\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableGUI_015.CAT03_NOT_OVERDUEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string CAT03_OVERDUE {
                get {
                    try {
                        return ((string)(this[this.tableGUI_015.CAT03_OVERDUEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'CAT03_OVERDUE\' in table \'GUI_015\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableGUI_015.CAT03_OVERDUEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string CAT04_AMOUNT {
                get {
                    try {
                        return ((string)(this[this.tableGUI_015.CAT04_AMOUNTColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'CAT04_AMOUNT\' in table \'GUI_015\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableGUI_015.CAT04_AMOUNTColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string CAT04_NOT_OVERDUE {
                get {
                    try {
                        return ((string)(this[this.tableGUI_015.CAT04_NOT_OVERDUEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'CAT04_NOT_OVERDUE\' in table \'GUI_015\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableGUI_015.CAT04_NOT_OVERDUEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string CAT04_OVERDUE {
                get {
                    try {
                        return ((string)(this[this.tableGUI_015.CAT04_OVERDUEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'CAT04_OVERDUE\' in table \'GUI_015\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableGUI_015.CAT04_OVERDUEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string CAT05_AMOUNT {
                get {
                    try {
                        return ((string)(this[this.tableGUI_015.CAT05_AMOUNTColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'CAT05_AMOUNT\' in table \'GUI_015\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableGUI_015.CAT05_AMOUNTColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string CAT05_NOT_OVERDUE {
                get {
                    try {
                        return ((string)(this[this.tableGUI_015.CAT05_NOT_OVERDUEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'CAT05_NOT_OVERDUE\' in table \'GUI_015\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableGUI_015.CAT05_NOT_OVERDUEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string CAT05_OVERDUE {
                get {
                    try {
                        return ((string)(this[this.tableGUI_015.CAT05_OVERDUEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'CAT05_OVERDUE\' in table \'GUI_015\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableGUI_015.CAT05_OVERDUEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string POINT {
                get {
                    try {
                        return ((string)(this[this.tableGUI_015.POINTColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'POINT\' in table \'GUI_015\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableGUI_015.POINTColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string AMOUNT_TOTAL {
                get {
                    try {
                        return ((string)(this[this.tableGUI_015.AMOUNT_TOTALColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'AMOUNT_TOTAL\' in table \'GUI_015\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableGUI_015.AMOUNT_TOTALColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string AMOUNT_TOTAL_NOT_OVERDUE {
                get {
                    try {
                        return ((string)(this[this.tableGUI_015.AMOUNT_TOTAL_NOT_OVERDUEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'AMOUNT_TOTAL_NOT_OVERDUE\' in table \'GUI_015\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableGUI_015.AMOUNT_TOTAL_NOT_OVERDUEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string SLA50PERCEN {
                get {
                    try {
                        return ((string)(this[this.tableGUI_015.SLA50PERCENColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'SLA50PERCEN\' in table \'GUI_015\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableGUI_015.SLA50PERCENColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string POINT_OF_INTENSIVE {
                get {
                    try {
                        return ((string)(this[this.tableGUI_015.POINT_OF_INTENSIVEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'POINT_OF_INTENSIVE\' in table \'GUI_015\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableGUI_015.POINT_OF_INTENSIVEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string TOTAL_AMOUNT {
                get {
                    try {
                        return ((string)(this[this.tableGUI_015.TOTAL_AMOUNTColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'TOTAL_AMOUNT\' in table \'GUI_015\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableGUI_015.TOTAL_AMOUNTColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string CAT06_AMOUNT {
                get {
                    try {
                        return ((string)(this[this.tableGUI_015.CAT06_AMOUNTColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'CAT06_AMOUNT\' in table \'GUI_015\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableGUI_015.CAT06_AMOUNTColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string CAT06_NOT_OVERDUE {
                get {
                    try {
                        return ((string)(this[this.tableGUI_015.CAT06_NOT_OVERDUEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'CAT06_NOT_OVERDUE\' in table \'GUI_015\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableGUI_015.CAT06_NOT_OVERDUEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string CAT06_OVERDUE {
                get {
                    try {
                        return ((string)(this[this.tableGUI_015.CAT06_OVERDUEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'CAT06_OVERDUE\' in table \'GUI_015\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableGUI_015.CAT06_OVERDUEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string CAL30PERCEN {
                get {
                    try {
                        return ((string)(this[this.tableGUI_015.CAL30PERCENColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'CAL30PERCEN\' in table \'GUI_015\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableGUI_015.CAL30PERCENColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsROW_NONull() {
                return this.IsNull(this.tableGUI_015.ROW_NOColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetROW_NONull() {
                this[this.tableGUI_015.ROW_NOColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsBRANCHNull() {
                return this.IsNull(this.tableGUI_015.BRANCHColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetBRANCHNull() {
                this[this.tableGUI_015.BRANCHColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsAMOUNTNull() {
                return this.IsNull(this.tableGUI_015.AMOUNTColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetAMOUNTNull() {
                this[this.tableGUI_015.AMOUNTColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsCAT01_AMOUNTNull() {
                return this.IsNull(this.tableGUI_015.CAT01_AMOUNTColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetCAT01_AMOUNTNull() {
                this[this.tableGUI_015.CAT01_AMOUNTColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsCAT01_NOT_OVERDUENull() {
                return this.IsNull(this.tableGUI_015.CAT01_NOT_OVERDUEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetCAT01_NOT_OVERDUENull() {
                this[this.tableGUI_015.CAT01_NOT_OVERDUEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsCAT01_OVERDUENull() {
                return this.IsNull(this.tableGUI_015.CAT01_OVERDUEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetCAT01_OVERDUENull() {
                this[this.tableGUI_015.CAT01_OVERDUEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsCAT02_AMOUNTNull() {
                return this.IsNull(this.tableGUI_015.CAT02_AMOUNTColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetCAT02_AMOUNTNull() {
                this[this.tableGUI_015.CAT02_AMOUNTColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsCAT02_NOT_OVERDUENull() {
                return this.IsNull(this.tableGUI_015.CAT02_NOT_OVERDUEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetCAT02_NOT_OVERDUENull() {
                this[this.tableGUI_015.CAT02_NOT_OVERDUEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsCAT02_OVERDUENull() {
                return this.IsNull(this.tableGUI_015.CAT02_OVERDUEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetCAT02_OVERDUENull() {
                this[this.tableGUI_015.CAT02_OVERDUEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsCAT03_AMOUNTNull() {
                return this.IsNull(this.tableGUI_015.CAT03_AMOUNTColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetCAT03_AMOUNTNull() {
                this[this.tableGUI_015.CAT03_AMOUNTColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsCAT03_NOT_OVERDUENull() {
                return this.IsNull(this.tableGUI_015.CAT03_NOT_OVERDUEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetCAT03_NOT_OVERDUENull() {
                this[this.tableGUI_015.CAT03_NOT_OVERDUEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsCAT03_OVERDUENull() {
                return this.IsNull(this.tableGUI_015.CAT03_OVERDUEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetCAT03_OVERDUENull() {
                this[this.tableGUI_015.CAT03_OVERDUEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsCAT04_AMOUNTNull() {
                return this.IsNull(this.tableGUI_015.CAT04_AMOUNTColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetCAT04_AMOUNTNull() {
                this[this.tableGUI_015.CAT04_AMOUNTColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsCAT04_NOT_OVERDUENull() {
                return this.IsNull(this.tableGUI_015.CAT04_NOT_OVERDUEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetCAT04_NOT_OVERDUENull() {
                this[this.tableGUI_015.CAT04_NOT_OVERDUEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsCAT04_OVERDUENull() {
                return this.IsNull(this.tableGUI_015.CAT04_OVERDUEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetCAT04_OVERDUENull() {
                this[this.tableGUI_015.CAT04_OVERDUEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsCAT05_AMOUNTNull() {
                return this.IsNull(this.tableGUI_015.CAT05_AMOUNTColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetCAT05_AMOUNTNull() {
                this[this.tableGUI_015.CAT05_AMOUNTColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsCAT05_NOT_OVERDUENull() {
                return this.IsNull(this.tableGUI_015.CAT05_NOT_OVERDUEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetCAT05_NOT_OVERDUENull() {
                this[this.tableGUI_015.CAT05_NOT_OVERDUEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsCAT05_OVERDUENull() {
                return this.IsNull(this.tableGUI_015.CAT05_OVERDUEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetCAT05_OVERDUENull() {
                this[this.tableGUI_015.CAT05_OVERDUEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsPOINTNull() {
                return this.IsNull(this.tableGUI_015.POINTColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetPOINTNull() {
                this[this.tableGUI_015.POINTColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsAMOUNT_TOTALNull() {
                return this.IsNull(this.tableGUI_015.AMOUNT_TOTALColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetAMOUNT_TOTALNull() {
                this[this.tableGUI_015.AMOUNT_TOTALColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsAMOUNT_TOTAL_NOT_OVERDUENull() {
                return this.IsNull(this.tableGUI_015.AMOUNT_TOTAL_NOT_OVERDUEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetAMOUNT_TOTAL_NOT_OVERDUENull() {
                this[this.tableGUI_015.AMOUNT_TOTAL_NOT_OVERDUEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsSLA50PERCENNull() {
                return this.IsNull(this.tableGUI_015.SLA50PERCENColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetSLA50PERCENNull() {
                this[this.tableGUI_015.SLA50PERCENColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsPOINT_OF_INTENSIVENull() {
                return this.IsNull(this.tableGUI_015.POINT_OF_INTENSIVEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetPOINT_OF_INTENSIVENull() {
                this[this.tableGUI_015.POINT_OF_INTENSIVEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsTOTAL_AMOUNTNull() {
                return this.IsNull(this.tableGUI_015.TOTAL_AMOUNTColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetTOTAL_AMOUNTNull() {
                this[this.tableGUI_015.TOTAL_AMOUNTColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsCAT06_AMOUNTNull() {
                return this.IsNull(this.tableGUI_015.CAT06_AMOUNTColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetCAT06_AMOUNTNull() {
                this[this.tableGUI_015.CAT06_AMOUNTColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsCAT06_NOT_OVERDUENull() {
                return this.IsNull(this.tableGUI_015.CAT06_NOT_OVERDUEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetCAT06_NOT_OVERDUENull() {
                this[this.tableGUI_015.CAT06_NOT_OVERDUEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsCAT06_OVERDUENull() {
                return this.IsNull(this.tableGUI_015.CAT06_OVERDUEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetCAT06_OVERDUENull() {
                this[this.tableGUI_015.CAT06_OVERDUEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsCAL30PERCENNull() {
                return this.IsNull(this.tableGUI_015.CAL30PERCENColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetCAL30PERCENNull() {
                this[this.tableGUI_015.CAL30PERCENColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        public class GUI_015RowChangeEvent : global::System.EventArgs {
            
            private GUI_015Row eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public GUI_015RowChangeEvent(GUI_015Row row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public GUI_015Row Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591